### PR TITLE
Nav

### PR DESCRIPTION
**Pull request by DrewGregory**

### CODE REVIEW

**Comment by samjgorman** [comment]
I had to update npm in order for yarn serve to work on my browser-- I'm assuming that's why it's including a 10,000+ addition to a json file?  would love your take on what's going on there @DrewGregory 

Our Navbar is not yet responsive-- some of that is because it's written with PX, and some of that is because we'll have to design a mobile navbar, triggered by a media query.

**Comment by DrewGregory** [comment]
What do you mean by responsive?

**Comment by kshen6** [comment]
Do you want the hamburger icon for mobile devices? Or do you simply mean the float: left, float: right type selectors?

**Comment by kshen6** [comment]
@samjgorman  What's the json file called? The only JSON file we should have in this repo is package.json which directs npm/yarn in managing dependencies, and when you run `yarn` it installs any required dependencies in node_modules/

**Comment by DrewGregory** [comment]
He's referring to the yarn-lock.json file. I added it in because the [yarn docs](https://yarnpkg.com/lang/en/docs/yarn-lock/)  say it should  be included.

**Comment by samjgorman** [comment]
@kshen6 Yeah, we'll want a hamburger icon instead--I'm planning to create wireframes for mobile by thursday that we can work from.  

@DrewGregory responsive as in equally usable from a mobile deveice as from desktop.  Currently, our navbar isn't very usable after being reduced to about half of desktop width.

**Comment by DrewGregory** [comment]
Gotcha. I think this will be something will take on once desktop is finished. Otherwise, are we ready to merge?

**Comment by DrewGregory** [comment]
I just added the scroll shadow. I didn't notice it before.

**Pull request merged**
